//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// Microsoft.VSDesigner generó automáticamente este código fuente, versión=4.0.30319.42000.
// 
#pragma warning disable 1591

namespace CSF.CITASWEB.WS.wsprecisa {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="Service1Soap", Namespace="http://tempuri.org/")]
    public partial class Service1 : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private clSeguridad clSeguridadValueField;
        
        private System.Threading.SendOrPostCallback SrvResultadoPdfOperationCompleted;
        
        private System.Threading.SendOrPostCallback listarAtencionesOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public Service1() {
            this.Url = global::CSF.CITASWEB.WS.Properties.Settings.Default.eureka_SanaWS_wsprecisa_Service1;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public clSeguridad clSeguridadValue {
            get {
                return this.clSeguridadValueField;
            }
            set {
                this.clSeguridadValueField = value;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event SrvResultadoPdfCompletedEventHandler SrvResultadoPdfCompleted;
        
        /// <remarks/>
        public event listarAtencionesCompletedEventHandler listarAtencionesCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("clSeguridadValue")]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/SrvResultadoPdf", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public CERetorno[] SrvResultadoPdf(string usuario, string Contrasena, string NroPeticion) {
            object[] results = this.Invoke("SrvResultadoPdf", new object[] {
                        usuario,
                        Contrasena,
                        NroPeticion});
            return ((CERetorno[])(results[0]));
        }
        
        /// <remarks/>
        public void SrvResultadoPdfAsync(string usuario, string Contrasena, string NroPeticion) {
            this.SrvResultadoPdfAsync(usuario, Contrasena, NroPeticion, null);
        }
        
        /// <remarks/>
        public void SrvResultadoPdfAsync(string usuario, string Contrasena, string NroPeticion, object userState) {
            if ((this.SrvResultadoPdfOperationCompleted == null)) {
                this.SrvResultadoPdfOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSrvResultadoPdfOperationCompleted);
            }
            this.InvokeAsync("SrvResultadoPdf", new object[] {
                        usuario,
                        Contrasena,
                        NroPeticion}, this.SrvResultadoPdfOperationCompleted, userState);
        }
        
        private void OnSrvResultadoPdfOperationCompleted(object arg) {
            if ((this.SrvResultadoPdfCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.SrvResultadoPdfCompleted(this, new SrvResultadoPdfCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("clSeguridadValue")]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/listarAtenciones", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public CEAtenciones[] listarAtenciones(string TipoDocumento, string Documento, string FechaInicio, string FechaFin) {
            object[] results = this.Invoke("listarAtenciones", new object[] {
                        TipoDocumento,
                        Documento,
                        FechaInicio,
                        FechaFin});
            return ((CEAtenciones[])(results[0]));
        }
        
        /// <remarks/>
        public void listarAtencionesAsync(string TipoDocumento, string Documento, string FechaInicio, string FechaFin) {
            this.listarAtencionesAsync(TipoDocumento, Documento, FechaInicio, FechaFin, null);
        }
        
        /// <remarks/>
        public void listarAtencionesAsync(string TipoDocumento, string Documento, string FechaInicio, string FechaFin, object userState) {
            if ((this.listarAtencionesOperationCompleted == null)) {
                this.listarAtencionesOperationCompleted = new System.Threading.SendOrPostCallback(this.OnlistarAtencionesOperationCompleted);
            }
            this.InvokeAsync("listarAtenciones", new object[] {
                        TipoDocumento,
                        Documento,
                        FechaInicio,
                        FechaFin}, this.listarAtencionesOperationCompleted, userState);
        }
        
        private void OnlistarAtencionesOperationCompleted(object arg) {
            if ((this.listarAtencionesCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.listarAtencionesCompleted(this, new listarAtencionesCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9037.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://tempuri.org/", IsNullable=false)]
    public partial class clSeguridad : System.Web.Services.Protocols.SoapHeader {
        
        private string stTokenField;
        
        private string autenticacionTokenField;
        
        private System.Xml.XmlAttribute[] anyAttrField;
        
        /// <remarks/>
        public string stToken {
            get {
                return this.stTokenField;
            }
            set {
                this.stTokenField = value;
            }
        }
        
        /// <remarks/>
        public string AutenticacionToken {
            get {
                return this.autenticacionTokenField;
            }
            set {
                this.autenticacionTokenField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyAttributeAttribute()]
        public System.Xml.XmlAttribute[] AnyAttr {
            get {
                return this.anyAttrField;
            }
            set {
                this.anyAttrField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9037.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class CEAtenciones {
        
        private string ordenAtencionField;
        
        private string peticionField;
        
        private string sedeField;
        
        private string medicoField;
        
        private string especialidadField;
        
        private System.DateTime fechaCreacionField;
        
        private string situacionField;
        
        /// <remarks/>
        public string OrdenAtencion {
            get {
                return this.ordenAtencionField;
            }
            set {
                this.ordenAtencionField = value;
            }
        }
        
        /// <remarks/>
        public string peticion {
            get {
                return this.peticionField;
            }
            set {
                this.peticionField = value;
            }
        }
        
        /// <remarks/>
        public string Sede {
            get {
                return this.sedeField;
            }
            set {
                this.sedeField = value;
            }
        }
        
        /// <remarks/>
        public string Medico {
            get {
                return this.medicoField;
            }
            set {
                this.medicoField = value;
            }
        }
        
        /// <remarks/>
        public string especialidad {
            get {
                return this.especialidadField;
            }
            set {
                this.especialidadField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime FechaCreacion {
            get {
                return this.fechaCreacionField;
            }
            set {
                this.fechaCreacionField = value;
            }
        }
        
        /// <remarks/>
        public string Situacion {
            get {
                return this.situacionField;
            }
            set {
                this.situacionField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9037.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class CERetorno {
        
        private string codErrorField;
        
        private string desErrorField;
        
        private string resultadoField;
        
        /// <remarks/>
        public string CodError {
            get {
                return this.codErrorField;
            }
            set {
                this.codErrorField = value;
            }
        }
        
        /// <remarks/>
        public string DesError {
            get {
                return this.desErrorField;
            }
            set {
                this.desErrorField = value;
            }
        }
        
        /// <remarks/>
        public string Resultado {
            get {
                return this.resultadoField;
            }
            set {
                this.resultadoField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    public delegate void SrvResultadoPdfCompletedEventHandler(object sender, SrvResultadoPdfCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class SrvResultadoPdfCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal SrvResultadoPdfCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public CERetorno[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((CERetorno[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    public delegate void listarAtencionesCompletedEventHandler(object sender, listarAtencionesCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class listarAtencionesCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal listarAtencionesCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public CEAtenciones[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((CEAtenciones[])(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591